services:
  backend:
    build:
      context: ./backend
    container_name: saaSify-backend
    ports:
      - "10000:10000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: saaSify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped